<script setup>
import { onMounted, ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import MobileLayout from '@/layouts/MobileLayout.vue'
import { find,create,update } from '@/services/students'
import { can } from '@/services/permissions'
const route=useRoute(),router=useRouter(),editing=!!route.params.id
const form=ref({name:'',cpf:'',birth_date:'',responsible:'',contact:'',password:'',password_confirmation:''}),loading=ref(false),errorMessage=ref('')
onMounted(async()=>{if(!editing)return;try{const r=await find(route.params.id);const s=r?.student||{};form.value={...form.value,name:s.name||'',cpf:s.cpf||'',birth_date:s.birth_date||'',responsible:s.responsible||s.responsible_contact||'',contact:s.contact||''}}catch(e){errorMessage.value='Não foi possível carregar o estudante.'}})
const save=async()=>{if(form.value.password!==form.value.password_confirmation){errorMessage.value='As senhas não coincidem.';return}if(!editing&&!form.value.password){errorMessage.value='Informe uma senha para assinatura digital.';return}loading.value=true;try{const payload={...form.value};if(editing)await update(route.params.id,payload);else{const r=await create(payload);await router.push(`/mobile/students/${r.student?.id||''}`);return}await router.push(`/mobile/students/${route.params.id}`)}catch(e){errorMessage.value=e.response?.data?.errors?.join(', ')||'Não foi possível salvar o estudante.'}finally{loading.value=false}}
</script>
<template><MobileLayout :mobile-title="editing?'Editar estudante':'Novo estudante'"><form @submit.prevent="save" class="space-y-4">
<div class="rounded-xl bg-white p-4 shadow-sm"><h2 class="font-semibold">Dados pessoais</h2><div class="mt-4 space-y-3"><label class="block text-sm font-medium">Nome<input v-model="form.name" required class="mt-1 w-full rounded-lg border px-3 py-3"></label><label class="block text-sm font-medium">CPF<input v-model="form.cpf" required class="mt-1 w-full rounded-lg border px-3 py-3"></label><label class="block text-sm font-medium">Data de nascimento<input v-model="form.birth_date" type="date" required class="mt-1 w-full rounded-lg border px-3 py-3"></label><label class="block text-sm font-medium">Responsável<input v-model="form.responsible" class="mt-1 w-full rounded-lg border px-3 py-3"></label><label class="block text-sm font-medium">Contato<input v-model="form.contact" class="mt-1 w-full rounded-lg border px-3 py-3"></label></div></div>
<div class="rounded-xl bg-white p-4 shadow-sm"><h2 class="font-semibold">Assinatura digital</h2><div class="mt-4 space-y-3"><input v-model="form.password" type="password" :required="!editing" placeholder="Senha" class="w-full rounded-lg border px-3 py-3"><input v-model="form.password_confirmation" type="password" :required="!editing" placeholder="Confirmar senha" class="w-full rounded-lg border px-3 py-3"></div></div>
<div v-if="errorMessage" class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ errorMessage }}</div><div class="grid grid-cols-2 gap-2"><RouterLink :to="editing?`/mobile/students/${route.params.id}`:'/mobile/students'" class="rounded-lg bg-gray-100 px-4 py-3 text-center">Cancelar</RouterLink><button :disabled="loading||(editing?!can('students','update'):!can('students','create'))" class="rounded-lg bg-green-600 px-4 py-3 text-white disabled:opacity-50">{{loading?'Salvando...':'Salvar'}}</button></div>
</form></MobileLayout></template>