# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '4.0.7'

gem 'bcrypt', '~> 3.1.19'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'cancancan'
gem 'carrierwave'
gem 'devise', '>= 4.7.1'
gem 'devise-i18n'
gem 'devise-jwt'
gem 'figaro'
gem 'friendly_id', '~> 5.7.0'
gem 'groupdate'
gem 'httparty'
gem 'kaminari'
gem 'loofah', '>= 2.2.3'
gem 'mimemagic', '~> 0.4.3'
gem 'mini_magick', '>= 4.11.0'
gem 'nokogiri', '>= 1.13.4'
gem 'pg'
gem 'puma', '~> 6.4'
gem 'rack', '>= 2.2.6.3'
gem 'rack-cors'
gem 'rails', '~> 8.1.0'
gem 'rails-i18n'
gem 'randumb'
gem 'rubyzip', '>= 1.3.0'
gem 'search_cop'
gem 'seed_migration'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'whenever', require: false
gem 'json', '~> 2.11.3'

group :development, :test do
  gem 'binding_of_caller'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_rewinder'
  gem 'email_spec'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'fuubar'
  gem 'rspec-rails', '~> 7.0.1'
  gem 'shoulda-matchers'
  gem 'simplecov', '~> 1.3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1.0'
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'brakeman'
  gem 'listen'
  gem 'pry-byebug'
  gem 'rails_best_practices'
  gem 'rails-erd'
  gem 'rb-readline'
  gem 'rubocop'
  gem 'rubocop-faker'
  gem 'rubocop-rails', require: false
  gem 'rubycritic'
  gem 'web-console'
end
