# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.10'

gem 'bcrypt', '~> 3.1.19'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'cancancan'
gem 'carrierwave'
gem 'devise', '>= 4.7.1'
gem 'devise-i18n'
gem 'devise-jwt'
gem 'erubis'
gem 'figaro'
gem 'friendly_id', '~> 5.5.0'
gem 'groupdate'
gem 'htmlcompressor'
gem 'httparty'
gem 'jbuilder', '~> 2.11'
gem 'kaminari'
gem 'loofah', '>= 2.2.3'
gem 'mechanize'
gem 'mimemagic', '~> 0.3.10'
gem 'mini_magick', '>= 4.11.0'
gem 'nokogiri', '>= 1.13.4'
gem 'pdfkit'
gem 'pg'
gem 'puma', '~> 6.4'
gem 'rack', '>= 2.2.6.3'
gem 'rack-cors'
gem 'rails', '~> 7'
gem 'rails-env'
# gem 'railties', '~> 7.0'
gem 'rails-i18n'
gem 'randumb'
gem 'rubyzip', '>= 1.3.0'
gem 'search_cop'
gem 'seed_migration'
gem 'spreadsheet'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'whenever', require: false
gem 'wkhtmltopdf-binary'
gem 'json', '~> 2.11.3'

group :development, :test do
  gem 'binding_of_caller'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'capybara', '>= 2.15'
  gem 'database_rewinder'
  gem 'email_spec'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'fuubar'
  gem 'mini_racer', '~> 0.6.3'
  gem 'rails-controller-testing'
  gem 'regressor', github: 'luizpicolo/regressor', branch: 'UpdateFakeGem'
  gem 'rspec-rails', '~> 7.0.1'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'simplecov', '~> 0.22.0'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1.0'
  gem 'webdrivers'
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'brakeman'
  gem 'listen'
  gem 'pry-byebug'
  gem 'rails_best_practices'
  gem 'rails-erd'
  gem 'rb-readline'
  gem 'rubocop'
  gem 'rubocop-faker'
  gem 'rubocop-rails', require: false
  gem 'rubycritic'
  gem 'web-console'
end

group :production do
  gem 'rails_12factor'
  gem 'turnout'
end
