services:
  sigoe-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigoe-ui
    ports:
      - "8080:3000"
    environment:
      PORT: 3000
    restart: unless-stopped